### ISSUE TITLE
Error after upgrade to version 0.0.23

### ISSUE THREAD

**Issue by Restless-ET** [fmarcia/UglifyCSS#44]
This is the message I'm getting:
```
Error Output:
/usr/local/lib/node_modules/uglifycss/uglifycss-lib.js:36
var pathResolve = PATH_SEP === "/" ? path.posix.resolve : path.win32.resolve;
                                               ^
TypeError: Cannot read property 'resolve' of undefined
      at Object.<anonymous> (/usr/local/lib/node_modules/uglifycss/uglifycss-lib.js:35:48)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Module.require (module.js:364:17)
      at require (module.js:380:17)
      at Object.<anonymous> (/usr/local/lib/node_modules/uglifycss/index.js:27:18)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
```

I've tried v0.0.22 and didn't work either. v0.0.21 is fine.

This seems to be related to https://github.com/fmarcia/UglifyCSS/commit/53b82d376c79ea993b2ca2de0f90d1156bb89b12

If any more data is needed please let me know.

Kind regards,

**Comment by fmarcia** [comment]
Which version of NodeJS do you use?

I checked with v5.12.0 and everything worked fine.

**Comment by hugues-b** [comment]
Hi fmarcia,

I've the same problem, my node version is v6.8.1.

Best regards

**Comment by fmarcia** [comment]
Thanks for your feedback. I use v6.8.1 as well on another laptop. Weird. According to the documentation, path.posix was added in v0.11.15 and path.win32 in v0.7.9.

**Comment by fmarcia** [comment]
Weird, it works on another laptop with v6.8.1 as well. According to node doc, path.posix and path.win32 are there since v0.11.15.
